<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPUALVIW0287" name="apitest.ReqResTest" tests="11" failures="0" timestamp="07 Feb 2018 15:39:47 GMT" time="13.971" errors="1">
  <testcase name="verifyResourceDataById" time="1.247" classname="apitest.ReqResTest"/>
  <testcase name="verifyUsersAmountOnPage" time="0.641" classname="apitest.ReqResTest"/>
  <testcase name="verifyUserDeleteById" time="0.371" classname="apitest.ReqResTest"/>
  <testcase name="verifyUserNamesById" time="0.434" classname="apitest.ReqResTest"/>
  <testcase name="verifyUserPresenceById" time="0.658" classname="apitest.ReqResTest"/>
  <testcase name="verifyUserUpdate" time="0.592" classname="apitest.ReqResTest"/>
  <testcase name="verifyUserAbsenceById" time="0.532" classname="apitest.ReqResTest"/>
  <testcase name="verifyUserCreation" time="0.454" classname="apitest.ReqResTest"/>
  <testcase name="afterMethod" time="0.000" classname="apitest.ReqResTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerExceptionat ui.driver.Driver.quit(Driver.java:59)at apitest.BaseTest.afterMethod(BaseTest.java:29)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:208)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)]]>
    </error>
  </testcase> <!-- afterMethod -->
  <testcase name="getUserDataByPageTest" time="8.431" classname="apitest.ReqResTest"/>
  <testcase name="verifyUnsuccessfulLogin" time="0.611" classname="apitest.ReqResTest"/>
</testsuite> <!-- apitest.ReqResTest -->
